### ISSUE TITLE
Robot starting on the ground

### ISSUE THREAD

**Issue by graiola** [graiola/wolf-setup#13]
I am preparing a major release where the robot starts directly from the ground.
@itaouil could you be interested in testing this release? Also, are you using the ROS topic to control the robot? Because I am planning to create some ROS services to perform various actions like resetting the base or standing up etc... .

**Comment by itaouil** [comment]
Hi,

Yes, happy to try it out in simulation (if this is what you mean) :).

At the moment I am controlling the robot using the joy commands and velocities that obtain from my planner (without the joystick) but I am planning to change this and start controlling it using the twist interface as it is less cumbersome. But yes I am using ROS topics.

One more thing. Given I am using your controller for my thesis work, would it be possible to keep a clean branch with the current debians so that in case the new release messes something up I still have a backup to go to for my work?

**Comment by graiola** [comment]
Sure! I created a new branch called itaouil starting from the current devel . The related debians are placed in the respective folder on dropbox:

https://www.dropbox.com/sh/njzikm4yk61w2r8/AABcoJi5BDrRb8Lhc_ftnH1ca?dl=0

If I may suggest you, always keep a working copy of this folder on your pc with the older debians.

Does that work for you?

**Comment by graiola** [comment]
I updated the debians in bionic with the new stand up and stand down procedure.

**Comment by itaouil** [comment]
> Sure! I created a new branch called itaouil starting from the current devel . The related debians are placed in the respective folder on dropbox:
> 
> https://www.dropbox.com/sh/njzikm4yk61w2r8/AABcoJi5BDrRb8Lhc_ftnH1ca?dl=0
> 
> If I may suggest you, always keep a working copy of this folder on your pc with the older debians.
> 
> Does that work for you?

Great thanks!

I just downloaded it and made a backup on my ssd drive.

**Comment by itaouil** [comment]
> I updated the debians in bionic with the new stand up and stand down procedure.

Amazing!

I will give it a try and update you tomorrow or so :)

**Comment by itaouil** [comment]
Hi @graiola,

I am sorry for the delay. I have got sidetracked with some stuff...

I did not forget about it though :).

**Comment by graiola** [comment]
np :)

**Comment by elpimous** [comment]
I'd like it too !
